services:
  annabelle-server:
    image: annabelle-server
    build:
      context: .
      target: ${BUILD_TARGET:-dev}
      additional_contexts:
        root-folder: ../
    volumes:
      - /app/node_modules
      - /app/server/node_modules
    env_file:
      - .env
    ports:
      - '8080:8080'
